title: "<span style='white-space: nowrap;'>Yuhan Ye <span style='font-size:90%;'>(å¶ç¦¹å«)</span></span>"
description: "<a href='mailto:yuhan.ye@usi.ch'>ğŸ“« yuhan.ye@usi.ch</a> â”‚ <a href='https://www.linkedin.com/in/yuhan-ye77/'>LinkedIn</a> â”‚ <a href='https://www.sfi.ch/en/people/yuhan-ye'>SFI Profile</a> â”‚ <a href='https://search.usi.ch/en/people/12fe19968bc63b6bdbe84d3eea7a5a4c/ye-yuhan'>USI Profile</a>"
theme: jekyll-theme-minimal
logo: /assets/profile.JPG
show_downloads: false
github:
  is_project_page: false
